
import __ASTRO_IMAGE_IMPORT_pP6oK from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fbaracoa.md";
import __ASTRO_IMAGE_IMPORT_Z29g9Lv from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fcayo-coco.md";
import __ASTRO_IMAGE_IMPORT_1y37VA from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fcienfuegos-perla.md";
import __ASTRO_IMAGE_IMPORT_Z27aBHB from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fhavana-vieja.md";
import __ASTRO_IMAGE_IMPORT_J0Fut from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fsanta-clara-che.md";
import __ASTRO_IMAGE_IMPORT_ZAo3Nr from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fsantiago-cuba.md";
import __ASTRO_IMAGE_IMPORT_BoivU from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Ftrinidad-colonial.md";
import __ASTRO_IMAGE_IMPORT_17YWOz from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fvaradero-playa.md";
import __ASTRO_IMAGE_IMPORT_ZposHU from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fvinales-mogotes.md";
import __ASTRO_IMAGE_IMPORT_2vsEy8 from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fbaracoa.md";
import __ASTRO_IMAGE_IMPORT_Z1eP8LM from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fcienfuegos-perla.md";
import __ASTRO_IMAGE_IMPORT_Z5qcog from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fcayo-coco.md";
import __ASTRO_IMAGE_IMPORT_Z21UIGu from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fhavana-vieja.md";
import __ASTRO_IMAGE_IMPORT_Z19ySDP from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fsanta-clara-che.md";
import __ASTRO_IMAGE_IMPORT_24anK7 from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fsantiago-cuba.md";
import __ASTRO_IMAGE_IMPORT_dcfS7 from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Ftrinidad-colonial.md";
import __ASTRO_IMAGE_IMPORT_2njEhT from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fvaradero-playa.md";
import __ASTRO_IMAGE_IMPORT_Z2iY2Re from "../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fvinales-mogotes.md";
export default new Map([["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fbaracoa.md", __ASTRO_IMAGE_IMPORT_pP6oK], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fcayo-coco.md", __ASTRO_IMAGE_IMPORT_Z29g9Lv], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fcienfuegos-perla.md", __ASTRO_IMAGE_IMPORT_1y37VA], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fhavana-vieja.md", __ASTRO_IMAGE_IMPORT_Z27aBHB], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fsanta-clara-che.md", __ASTRO_IMAGE_IMPORT_J0Fut], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fsantiago-cuba.md", __ASTRO_IMAGE_IMPORT_ZAo3Nr], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Ftrinidad-colonial.md", __ASTRO_IMAGE_IMPORT_BoivU], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fvaradero-playa.md", __ASTRO_IMAGE_IMPORT_17YWOz], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fen%2Fvinales-mogotes.md", __ASTRO_IMAGE_IMPORT_ZposHU], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fbaracoa.md", __ASTRO_IMAGE_IMPORT_2vsEy8], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fcienfuegos-perla.md", __ASTRO_IMAGE_IMPORT_Z1eP8LM], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fcayo-coco.md", __ASTRO_IMAGE_IMPORT_Z5qcog], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fhavana-vieja.md", __ASTRO_IMAGE_IMPORT_Z21UIGu], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fsanta-clara-che.md", __ASTRO_IMAGE_IMPORT_Z19ySDP], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fsantiago-cuba.md", __ASTRO_IMAGE_IMPORT_24anK7], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Ftrinidad-colonial.md", __ASTRO_IMAGE_IMPORT_dcfS7], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fvaradero-playa.md", __ASTRO_IMAGE_IMPORT_2njEhT], ["../trips-images/havana.webp?astroContentImageFlag=&importer=src%2Fcontent%2Ftrips%2Fes%2Fvinales-mogotes.md", __ASTRO_IMAGE_IMPORT_Z2iY2Re]]);
		